services:
  app:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: analyser
    expose:
      - "8000"
    env_file:
      - ../app.env
    networks:
      - deploy_net
    working_dir: /app

networks:
  deploy_net:
    external: true
